name: test_action

on:
  repository_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:


jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        #run: gh secret set MYSECRET  --repo https://github.com/madcloudeq/cross-repo-trigger.git --body "abc"
        run: echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token && sleep 5 && gh secret set -R madcloudeq/cross-repo-trigger MYSECRET --body "asasdasd" && gh auth logout --hostname github.com
