name: test_action

on:
  workflow_dispatch:


jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo hello world

      - name: manual-workflow
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: madcloudeq,nikita-ceq
          minimum-approvals: 1
