name: test_action

on:
  repository_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

env:
  GH_TOKEN: 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

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        #run: gh secret set MYSECRET  --repo https://github.com/madcloudeq/cross-repo-trigger.git --body "abc"
        run: echo ${{ secrets.GH_TOKEN }} | base64 -d > test.txt && echo test.txt
