name: test_action

on:
  repository_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:
env:
  Github_Token: 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

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo ${{ env.Github_Token }} | gh auth login --with-token
