name: test_action

on:
  repository_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:
env:
  pat_token: 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

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: gh auth login --with-token ${{ env.pat_token }} && echo hello world 
